---
- name: Add Mongo signing key
  tags: install
  apt_key:
    id: EA312927
    keyserver: keyserver.ubuntu.com
    state: present

- name: Add Mongo repository
  tags: install
  apt_repository:
    repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
    state: present
    filename: mongodb-org-3.2

- name: Install Mongo
  tags: install
  apt:
    name: mongodb-org
    update_cache: yes

- name: Enable Mongo
  tags: install
  systemd:
    name: mongod
    enabled: yes
    state: started
